version: "3.9"

services:
  # Redis service
  redis:
    image: "amd64/redis:latest"
    platform: linux/amd64
    restart: unless-stopped
    volumes:
      - redis_data:/data

  # MongoDB service
  mongodb:
    image: "amd64/mongo:4.4.6"
    platform: linux/amd64
    restart: always
    volumes:
      - mongodb_data:/data/db

  # Node API services
  thecultiverly:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /src/node_modules
    environment:
      PORT: 3000
      MONGO_URI: ${MONGO_URI} # Use the environment variable here
      REDIS_URL: ${REDIS_URL}
      REDIS_PORT: ${REDIS_PORT}
    depends_on:
      - mongodb
      - redis

volumes:
  mongodb_data:
  redis_data:
  app:
  node_modules:
